### PR TITLE
Move from LESS to SASS

### PR DESCRIPTION
**Pull request by carpeliam**
Now that there's an official SASS port for Bootstrap, we'd like to move from LESS to SASS, because SASS is managed by the Ruby community, and fits nicely within a Rails project. The sass-rails gem is also managed underneath the rails suite of repositories, and is likely to be more stable over time.

In adopting Bootstrap with SASS, we decided to move from the Bower component over to the Rails gem. This is because the gem in this case is actually managed underneath the Bootstrap suite of repositories, so it'll likely be kept up to date. The official Bootstrap component also had Sprockets code in it, so we'd really have to fight against the grain to use Bower with Bootstrap.

### CODE REVIEW

**Comment by eedrummer** [comment]
I think this may cause some of the icons to go missing. When switching to this branch, popHealth can't find /bootstrap/glyphicons-halflings-regular.ttf, /bootstrap/glyphicons-halflings-regular.svg. This messes up the patient icon next to the fraction.

**Comment by carpeliam** [comment]
@eedrummer I don't see this issue on a fresh install. I wonder if maybe you have an issue with your assets cache in `RAILS_ROOT/tmp/cache/assets`? Try running `rake assets:clobber` to remove this directory.

**Comment by eedrummer** [comment]
@carpeliam That worked. Thanks.

**Comment by eedrummer** [comment]
Rebased and merged

**Pull request closed without merging**
