### PR TITLE
Display measures with cms/nqf ids in the title

### PR DESCRIPTION
**Pull request by yoon**

### CODE REVIEW

**Comment by jmccloud** [comment]
I noticed that you've added the CMS id in the measure titles on the dashboard.  Can you tell me how you are uses these so we can find a more effective design presentation of these?  Does 'CMS' and the version number need to show up for every on the dashboard?

**Comment by yoon** [comment]
We use them to find measures - so CMS doesn't have to appear if we can differentiate the CMS and NQF ids - maybe by some sort of contrast: position, emphasis, or color come to mind. "CMS" doesn't need to show up, and the version number doesn't need to show immediately and may be deferred to a mouseover or click. If you're implying that they're long and cumbersome, I'm inclined to agree.

**Comment by rdingwell** [comment]
NQF ids should really not be used.  Not all of the measures have NQF ids but they all do have CMS ids.  We have been trying internally to standardize on using the CMS id.  

Jeff, "CMS" is part of the id in the measure so that is the way it comes out when displayed.  This is also how they are displayed on the ushik and oncprojecttracking sites so it would be best for us to maintain that consistency with the other tools.

**Comment by jmccloud** [comment]
Rob: Could we strip off the 'cms' from each measure?

When you are looking at the measures, do you recognize them by CMS id or name first?  If it's by name (i.e. Breast Cancer Screening), I would suggest we a tack it on the end of the measure in smaller text in a light gray box.

**Comment by rdingwell** [comment]
I look for ids over names.  You do not want to strip the CMS off of the id
either as there is overlap between the CMS and NQF ids and they do not
point to the same measures.

**Pull request merged**
